package importer

import (
	"regexp"
	"strconv"
	"strings"

	"github.com/fomeanator/elvin/tools/lvnconv/internal/articy"
)

// choice_effects.go gives each choice option a PREVIEW of what picking it
// awards — "+2 Роман" on the button — without executing anything. It reads
// the branch's own ops (already generated by the base converter), it never
// re-derives them: a hint that could drift from what the branch actually does
// would be worse than no hint.
//
// The window is bounded by the NEXT "choice" op, not by the first non-set/inc
// op: real content (demo_13_08_25) routinely runs several say/actor lines
// before the branch's stat change — sometimes 40+ ops in — so "stop at the
// first non-set/inc" found nothing at all. A branch runs linearly until the
// player's next real decision point, so that's the honest boundary.

const previewWindow = 150 // op budget per option — bounds the scan on a huge chapter

// AnnotateChoiceEffects scans every "choice" command's options and, for each
// one, previews the stat changes its target branch makes before the player's
// next choice — filtered to the project's configured stat keys (the
// template's trait pairs and its relationship namespace). Written as
// opt["effects"] = [{"label": "Роман", "delta": 2}, …] so the runtime can
// show it on the button. A project with no stats configured is untouched.
func AnnotateChoiceEffects(doc *articy.Doc, tpl *Template) {
	tpl = tpl.resolve()
	if len(tpl.Stats.Pairs) == 0 && tpl.Stats.RelationshipNamespace == "" {
		return
	}

	labelPos := map[string]int{}
	for i, c := range doc.Script {
		if c["op"] == "label" {
			if id, _ := c["id"].(string); id != "" {
				labelPos[id] = i
			}
		}
	}

	for _, c := range doc.Script {
		if c["op"] != "choice" {
			continue
		}
		opts, _ := c["options"].([]any)
		for _, o := range opts {
			opt, ok := o.(articy.Cmd)
			if !ok {
				continue
			}
			target := gotoTarget(opt)
			if target == "" {
				continue
			}
			pos, ok := labelPos[target]
			if !ok {
				continue
			}
			if effects := previewEffects(doc.Script, pos+1, tpl); len(effects) > 0 {
				opt["effects"] = effects
			}
		}
	}
}

// gotoTarget is the label an option jumps to on pick — its plain "goto", or
// (a [onetime] option) the goto step tucked inside its body.
func gotoTarget(opt articy.Cmd) string {
	if g, _ := opt["goto"].(string); g != "" {
		return g
	}
	if body, ok := opt["body"].([]any); ok {
		for _, b := range body {
			if bc, ok := b.(articy.Cmd); ok {
				if bc["op"] == "goto" {
					if g, _ := bc["label"].(string); g != "" {
						return g
					}
				}
			}
		}
	}
	return ""
}

// previewEffects sums the stat deltas a branch applies before the player's
// NEXT choice (or a previewWindow op budget, whichever comes first — a
// backstop against a pathologically long branch, not a real boundary; labels
// in between are just narrative bookmarks and don't end the window). Two
// authoring shapes both count: a plain "inc" op, and the self-referencing
// "X = X +1" convention this project actually uses (parsed by the base
// converter as set+expr because "X +1" isn't a literal value).
func previewEffects(script []articy.Cmd, start int, tpl *Template) []any {
	deltas := map[string]int{}
	var order []string

	limit := start + previewWindow
	if limit > len(script) {
		limit = len(script)
	}
	for i := start; i < limit; i++ {
		c := script[i]
		if c["op"] == "choice" {
			break // the player's next real decision — the honest boundary
		}
		key, _ := c["key"].(string)
		if key == "" {
			continue
		}
		var delta int
		switch c["op"] {
		case "inc":
			delta = asIntDelta(c["by"])
		case "set":
			if expr, _ := c["expr"].(string); expr != "" {
				delta = selfRefDelta(key, expr)
			}
		}
		if delta == 0 {
			continue
		}
		if _, ok := statLabel(key, tpl); !ok {
			continue
		}
		if _, seen := deltas[key]; !seen {
			order = append(order, key)
		}
		deltas[key] += delta
	}

	var out []any
	for _, key := range order {
		if d := deltas[key]; d != 0 {
			label, _ := statLabel(key, tpl)
			out = append(out, map[string]any{"label": label, "delta": d})
		}
	}
	return out
}

// reSelfRefDelta matches the tail of a self-referencing expr ("X +1", "X - 2")
// once the leading "X" (the key itself) has been stripped off.
var reSelfRefDelta = regexp.MustCompile(`^\s*([+-])\s*([0-9]+(?:\.[0-9]+)?)\s*$`)

// selfRefDelta recognizes "key = key +N" / "key = key -N" (the converter
// stores the RHS as expr since "key +N" isn't a pure literal): returns the
// signed integer delta, or 0 when expr isn't exactly this self-referencing
// shape (a real formula involving other variables previews nothing — safer
// than guessing).
func selfRefDelta(key, expr string) int {
	expr = strings.TrimSpace(expr)
	if !strings.HasPrefix(expr, key) {
		return 0
	}
	rest := strings.TrimSpace(strings.TrimPrefix(expr, key))
	m := reSelfRefDelta.FindStringSubmatch(rest)
	if m == nil {
		return 0
	}
	whole := strings.SplitN(m[2], ".", 2)[0] // integer part only — "+1.5" reads as +1 to a player
	n, err := strconv.Atoi(whole)
	if err != nil {
		return 0
	}
	if m[1] == "-" {
		n = -n
	}
	return n
}

// statLabel resolves a var key to its player-facing label IF it's one of the
// project's configured stats (a trait pair's pos/neg key, or a variable under
// the relationship namespace) — the same rule TitleStats uses to build
// title.stats, so a hint never mentions a stat the player can't see anywhere.
func statLabel(key string, tpl *Template) (string, bool) {
	for _, p := range tpl.Stats.Pairs {
		if key == p.PosKey {
			return p.PosLabel, true
		}
		if key == p.NegKey {
			return p.NegLabel, true
		}
	}
	if ns := tpl.Stats.RelationshipNamespace; ns != "" && strings.HasPrefix(key, ns+".") {
		name := strings.TrimPrefix(key, ns+".")
		if label := tpl.SpeakerNames[name]; label != "" {
			return label, true
		}
		return name, true
	}
	return "", false
}

func asIntDelta(v any) int {
	switch n := v.(type) {
	case int:
		return n
	case int64:
		return int(n)
	case float64:
		return int(n)
	}
	return 0
}
