package importer

import (
	"strings"

	"github.com/fomeanator/elvin/tools/lvnconv/internal/articy"
)

// choice_effects.go gives each choice option a PREVIEW of what picking it
// awards — "+2 Матвей" on the button — without executing anything. It reads
// the branch's own immediate ops (already generated by the base converter),
// it never re-derives them: a hint that could drift from what the branch
// actually does would be worse than no hint.

// AnnotateChoiceEffects scans every "choice" command's options and, for each
// one, previews the inc ops its target branch runs BEFORE any real content
// (say/bg/…) — filtered to the project's configured stat keys (the template's
// trait pairs and its relationship namespace). Written as
// opt["effects"] = [{"label": "Матвей", "delta": 2}, …] so the runtime can
// show it on the button. A project with no stats configured is untouched.
func AnnotateChoiceEffects(doc *articy.Doc, tpl *Template) {
	tpl = tpl.resolve()
	if len(tpl.Stats.Pairs) == 0 && tpl.Stats.RelationshipNamespace == "" {
		return
	}

	labelPos := map[string]int{}
	for i, c := range doc.Script {
		if c["op"] == "label" {
			if id, _ := c["id"].(string); id != "" {
				labelPos[id] = i
			}
		}
	}

	for _, c := range doc.Script {
		if c["op"] != "choice" {
			continue
		}
		opts, _ := c["options"].([]any)
		for _, o := range opts {
			opt, ok := o.(articy.Cmd)
			if !ok {
				continue
			}
			target := gotoTarget(opt)
			if target == "" {
				continue
			}
			pos, ok := labelPos[target]
			if !ok {
				continue
			}
			if effects := previewEffects(doc.Script, pos+1, tpl); len(effects) > 0 {
				opt["effects"] = effects
			}
		}
	}
}

// gotoTarget is the label an option jumps to on pick — its plain "goto", or
// (a [onetime] option) the goto step tucked inside its body.
func gotoTarget(opt articy.Cmd) string {
	if g, _ := opt["goto"].(string); g != "" {
		return g
	}
	if body, ok := opt["body"].([]any); ok {
		for _, b := range body {
			if bc, ok := b.(articy.Cmd); ok {
				if bc["op"] == "goto" {
					if g, _ := bc["label"].(string); g != "" {
						return g
					}
				}
			}
		}
	}
	return ""
}

// previewEffects scans forward from a branch's first op collecting inc deltas
// on configured stat keys, and stops at the first op that ISN'T set/inc —
// that op is real content, past the "immediate consequence of this choice"
// window. set ops are skipped (not previewed: an absolute assignment isn't an
// "award") but don't end the window — a choice often both flags a flag and
// increments a stat in the same lead-in.
func previewEffects(script []articy.Cmd, start int, tpl *Template) []any {
	var out []any
	for i := start; i < len(script); i++ {
		switch script[i]["op"] {
		case "inc":
			key, _ := script[i]["key"].(string)
			if label, ok := statLabel(key, tpl); ok {
				if delta := asIntDelta(script[i]["by"]); delta != 0 {
					out = append(out, map[string]any{"label": label, "delta": delta})
				}
			}
		case "set":
			// same window, not itself a preview-worthy award.
		default:
			return out
		}
	}
	return out
}

// statLabel resolves a var key to its player-facing label IF it's one of the
// project's configured stats (a trait pair's pos/neg key, or a variable under
// the relationship namespace) — the same rule TitleStats uses to build
// title.stats, so a hint never mentions a stat the player can't see anywhere.
func statLabel(key string, tpl *Template) (string, bool) {
	for _, p := range tpl.Stats.Pairs {
		if key == p.PosKey {
			return p.PosLabel, true
		}
		if key == p.NegKey {
			return p.NegLabel, true
		}
	}
	if ns := tpl.Stats.RelationshipNamespace; ns != "" && strings.HasPrefix(key, ns+".") {
		name := strings.TrimPrefix(key, ns+".")
		if label := tpl.SpeakerNames[name]; label != "" {
			return label, true
		}
		return name, true
	}
	return "", false
}

func asIntDelta(v any) int {
	switch n := v.(type) {
	case int:
		return n
	case int64:
		return int(n)
	case float64:
		return int(n)
	}
	return 0
}
